In [8]:
import pickle
import numpy as np
reg = pickle.load(open('rf_regressor_gridsearch.pkl', 'rb'))

n_quartos = input('entre com o numero de quartos')
area = input('entre com a area')
zona = input('entre com a zona')

zona_to_onehot = {'leste': np.array([1, 0, 0, 0]),
                  'norte': np.array([0, 1, 0, 0]),
                  'oeste': np.array([0, 0, 1, 0]),
                  'sul'  : np.array([0, 0, 0, 1])
                  }

n_quartos_log = np.log1p(int(n_quartos))
area_log = np.log1p(float(area))
zona_onehot = zona_to_onehot[zona]

/Users/wittmann/anaconda/envs/udacity-update/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.22.2.post1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/wittmann/anaconda/envs/udacity-update/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 0.22.2.post1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


entre com o numero de quartos2
entre com a area80
entre com a zonasul


In [9]:
zona_onehot

array([0, 0, 0, 1])

In [10]:
n_quartos_log

1.0986122886681098

In [11]:
area_log

4.394449154672439

In [17]:
np.expm1(reg.predict([[1, 0, 0, 0, np.log1p(2), np.log1p(80)]]))

array([1496.98834649])

In [13]:
np.expm1(reg.predict([np.r_[zona_onehot, n_quartos_log, area_log]]))

array([1929.87923049])

In [18]:
ls

app.py                       app_v1.py
app_v0.py                    flask101/
app_v1.ipynb                 rf_regressor_gridsearch.pkl


In [1]:
cd flask101

/Users/wittmann/awari-turmas/awari-calculadora-imoveis-may-20/4-deploy/flask101


In [2]:
ls

templates/


In [3]:
from flask import Flask, render_template

In [23]:
Flask?

In [24]:
__name__

'__main__'

In [4]:
app = Flask(__name__)

In [27]:
app?

In [36]:
app.route?

In [6]:
def index():
    return render_template('primeiro_app.html')

In [7]:
#index=app.route('/', algum_argumento=index)

In [9]:
# https://flask.palletsprojects.com/en/1.1.x/patterns/viewdecorators/
# https://www.python-course.eu/python3_decorators.php
@app.route('/')
def index():
    return render_template('primeiro_app.html')

In [10]:
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [31/Aug/2020 17:07:23] "GET / HTTP/1.1" 200 -


In [5]:
ls

app.py                       app_v1.py
app_step_by_step.ipynb       flask101/
app_v0.py                    rf_regressor_gridsearch.pkl


In [28]:
from flask import request

In [29]:
app = Flask(__name__)

In [30]:
# https://flask.palletsprojects.com/en/1.1.x/patterns/viewdecorators/
# https://www.python-course.eu/python3_decorators.php
@app.route('/')
def index():
    return render_template('segundo_app.html')

In [31]:
@app.route('/predict', methods=['POST'])
def predict():
    form_values = [x for x in request.form.values()]
    return render_template('segundo_app.html',
            prediction_text=form_values)

In [32]:
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [31/Aug/2020 17:46:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/Aug/2020 17:46:34] "POST /predict HTTP/1.1" 200 -


In [27]:
segundo_app = """
<!doctype html>
<html>
	<head>
		<title>Primeiro App</title>
	</head>
	<body>
		<div>Ola, este é o meu segundo app em Flask</div>
		<form action="{{ url_for('predict')}}" method="post">
        <input type="text" name="zona" placeholder="Zona" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Calcular!</button>
        {{ prediction_text }}
    </form>
	</body>
</html>
"""